frontend:
  port: 6000
  metricsport: 9091
  cert: ""
  key: ""

# Default backend used when no virtual host matches
backend:
  target: localhost:8000
  timeout: 10s
  scheme: http

# Virtual host specific backends
virtualhosts:
  "example.com":
    target: example-backend:8080
    timeout: 10s
    scheme: http
  "api.example.com":
    target: api-backend:8080
    timeout: 5s
    scheme: https

cache:
  maxobj: 1M
  maxcost: 1G

# Log level can be: debug, info, warn, error
loglevel: info