frontend:
  port: 6000
  metricsport: 1991
  cert: ""
  key: ""

# Default backend used when no virtual host matches
default_backend:
  target: http://www.varnish-software.com
  timeout: 10s

cache:
  maxobj: 1M
  maxcost: 1G
  # When true, requests to different hosts but with the same path will use the same cache entry
  ignorehost: true

# Log level can be: debug, info, warn, error
logging:
  level: error
  format: json