frontend:
  port: 8080
  metricsport: 9091
  cert: ""
  key: ""

backend:
  target: www.varnish-software.com:443
  timeout: 10s
  scheme: https

cache:
  maxobj: 1M
  maxcost: 1G

# Log level can be: debug, info, warn, error
loglevel: info